//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulletPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BulletPoint()
        {
            this.ScenarioIGSubTitles = new HashSet<ScenarioIGSubTitle>();
            this.ScenarioIGSubTitleBullets = new HashSet<ScenarioIGSubTitleBullet>();
            this.ScenarioSlideSubTitles = new HashSet<ScenarioSlideSubTitle>();
            this.ScenarioSlideSubTitleBullets = new HashSet<ScenarioSlideSubTitleBullet>();
        }
    
        public int IDBulletPoints { get; set; }
        public string Unicode { get; set; }
        public string ClassContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioIGSubTitle> ScenarioIGSubTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioIGSubTitleBullet> ScenarioIGSubTitleBullets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioSlideSubTitle> ScenarioSlideSubTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioSlideSubTitleBullet> ScenarioSlideSubTitleBullets { get; set; }
    }
}
