//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language1()
        {
            this.ScenarioInfoes = new HashSet<ScenarioInfo>();
            this.ScenarioInfoes1 = new HashSet<ScenarioInfo>();
        }
    
        public int IDLanguage { get; set; }
        public string LanguageCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioInfo> ScenarioInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioInfo> ScenarioInfoes1 { get; set; }
    }
}
