//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlideIGWebEntities : DbContext
    {
        public SlideIGWebEntities()
            : base("name=SlideIGWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BulletPoint> BulletPoints { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Scenario> Scenarios { get; set; }
        public virtual DbSet<ScenarioIG> ScenarioIGs { get; set; }
        public virtual DbSet<ScenarioIGSubTitle> ScenarioIGSubTitles { get; set; }
        public virtual DbSet<ScenarioIGSubTitleBullet> ScenarioIGSubTitleBullets { get; set; }
        public virtual DbSet<ScenarioIGTitle> ScenarioIGTitles { get; set; }
        public virtual DbSet<ScenarioInfo> ScenarioInfoes { get; set; }
        public virtual DbSet<ScenarioSlide> ScenarioSlides { get; set; }
        public virtual DbSet<ScenarioSlideSubTitle> ScenarioSlideSubTitles { get; set; }
        public virtual DbSet<ScenarioSlideSubTitleBullet> ScenarioSlideSubTitleBullets { get; set; }
        public virtual DbSet<ScenarioSlideTitle> ScenarioSlideTitles { get; set; }
        public virtual DbSet<SimulatorType> SimulatorTypes { get; set; }
    }
}
