//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioIG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioIG()
        {
            this.ScenarioIGTitles = new HashSet<ScenarioIGTitle>();
        }
    
        public int IDScenarioIG { get; set; }
        public Nullable<int> IDScenarioInfo { get; set; }
    
        public virtual ScenarioInfo ScenarioInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioIGTitle> ScenarioIGTitles { get; set; }
    }
}
