//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioSlideSubTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioSlideSubTitle()
        {
            this.ScenarioSlideSubTitleBullets = new HashSet<ScenarioSlideSubTitleBullet>();
        }
    
        public int IDScenarioSlideSubTitle { get; set; }
        public Nullable<int> IDScenarioSlideTitle { get; set; }
        public Nullable<int> IDBulletPoints { get; set; }
        public string Content { get; set; }
    
        public virtual BulletPoint BulletPoint { get; set; }
        public virtual ScenarioSlideTitle ScenarioSlideTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioSlideSubTitleBullet> ScenarioSlideSubTitleBullets { get; set; }
    }
}
