//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioIGSubTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioIGSubTitle()
        {
            this.ScenarioIGSubTitleBullets = new HashSet<ScenarioIGSubTitleBullet>();
        }
    
        public int IDScenarioIGSubTitle { get; set; }
        public Nullable<int> IDScenarioIGTitle { get; set; }
        public Nullable<int> IDBulletPoints { get; set; } = 1;
        public string Content { get; set; }
    
        public virtual BulletPoint BulletPoint { get; set; }
        public virtual ScenarioIGTitle ScenarioIGTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioIGSubTitleBullet> ScenarioIGSubTitleBullets { get; set; }
    }
}
