//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioInfo()
        {
            this.ScenarioIGs = new HashSet<ScenarioIG>();
            this.ScenarioSlides = new HashSet<ScenarioSlide>();
        }
    
        public int IDScenarioInfo { get; set; }
        public Nullable<int> IDScenario { get; set; }
        public Nullable<int> IDLanguage { get; set; }
        public Nullable<int> IDSimulatorType { get; set; }
        public string Title { get; set; }

        public virtual Language Language { get; set; }
        public virtual Language Language1 { get; set; }
        public virtual Scenario Scenario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioIG> ScenarioIGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioSlide> ScenarioSlides { get; set; }
    }
}
