//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioIGTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioIGTitle()
        {
            this.ScenarioIGSubTitles = new HashSet<ScenarioIGSubTitle>();
        }
    
        public int IDScenarioIGTitle { get; set; }
        public Nullable<int> IDScenarioIG { get; set; }
        public string Content { get; set; }
    
        public virtual ScenarioIG ScenarioIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioIGSubTitle> ScenarioIGSubTitles { get; set; }
    }
}
