//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioSlideTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScenarioSlideTitle()
        {
            this.ScenarioSlideSubTitles = new HashSet<ScenarioSlideSubTitle>();
        }
    
        public int IDScenarioSlideTitle { get; set; }
        public Nullable<int> IDScenarioSlide { get; set; }
        public string Content { get; set; }
    
        public virtual ScenarioSlide ScenarioSlide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioSlideSubTitle> ScenarioSlideSubTitles { get; set; }
    }
}
