//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioSlideSubTitleBullet
    {
        public int IDScenarioSlideSubTitleBullets { get; set; }
        public Nullable<int> IDScenarioSlideSubTitle { get; set; }
        public Nullable<int> IDBulletPoints { get; set; }
        public string Content { get; set; }
    
        public virtual BulletPoint BulletPoint { get; set; }
        public virtual ScenarioSlideSubTitle ScenarioSlideSubTitle { get; set; }
    }
}
