//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlideIGWebRetry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioIGSubTitleBullet
    {
        public int IDScenarioIGSubTitleBullets { get; set; }
        public Nullable<int> IDScenarioIGSubTitle { get; set; }
        public int IDBulletPoints { get; set; } = 1;
        public string Content { get; set; }
        public virtual BulletPoint BulletPoint { get; set; }
        public virtual ScenarioIGSubTitle ScenarioIGSubTitle { get; set; }
    }
}
